# Generated by Django 2.0.1 on 2019-09-24 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlieClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('scheme_name', models.CharField(max_length=30)),
                ('module_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flie_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name_generate.FlieClass')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name_generate.ProjectClass'),
        ),
        migrations.AddField(
            model_name='filename',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Project'),
        ),
    ]
