# Generated by Django 2.0.1 on 2019-09-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TechniFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(max_length=30, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Module')),
            ],
        ),
        migrations.RemoveField(
            model_name='filename',
            name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='module_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_class',
            new_name='projectclass',
        ),
        migrations.RenameField(
            model_name='projectclass',
            old_name='flie_class',
            new_name='flieclass',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scheme_name',
        ),
        migrations.DeleteModel(
            name='FileName',
        ),
        migrations.AddField(
            model_name='technifilename',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Project'),
        ),
        migrations.AddField(
            model_name='technifilename',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Scheme'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name_generate.Project'),
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name_generate.Project'),
        ),
    ]
