# Generated by Django 2.0.1 on 2019-10-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(upload_to='static', verbose_name='请上传正确格式excel文件'),
        ),
        migrations.AlterField(
            model_name='planfilename',
            name='result',
            field=models.CharField(max_length=60, null=True, verbose_name='文件编号'),
        ),
        migrations.AlterField(
            model_name='recordfilename',
            name='result',
            field=models.CharField(max_length=60, null=True, verbose_name='文件编号'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='result',
            field=models.CharField(max_length=50, verbose_name='文件编号'),
        ),
    ]
