# Generated by Django 2.0.1 on 2019-10-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0002_auto_20191010_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='时间'),
        ),
    ]
