# Generated by Django 2.0.1 on 2019-09-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0002_auto_20190924_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technifilename',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Module'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Scheme'),
        ),
    ]
