# Generated by Django 2.0.1 on 2019-09-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0003_auto_20190925_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flieclass',
            options={'verbose_name_plural': '文件分类'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name_plural': '模块表'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目列表'},
        ),
        migrations.AlterModelOptions(
            name='projectclass',
            options={'verbose_name_plural': '项目分类'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name_plural': '方案表'},
        ),
        migrations.AlterModelOptions(
            name='technifilename',
            options={'verbose_name_plural': '技术类文件'},
        ),
        migrations.AlterField(
            model_name='flieclass',
            name='name',
            field=models.CharField(max_length=30, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=30, verbose_name='模块名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='projectclass',
            name='name',
            field=models.CharField(max_length=30, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=30, verbose_name='方案名'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='name',
            field=models.CharField(max_length=30, verbose_name='文件名'),
        ),
    ]
