# Generated by Django 2.0.1 on 2019-09-30 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0004_auto_20190925_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '9'), ('10', '10')], max_length=30, null=True, verbose_name='阶段')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('name', models.CharField(max_length=30, verbose_name='文件名')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '计划类文件',
            },
        ),
        migrations.CreateModel(
            name='RecordFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('name', models.CharField(max_length=30, verbose_name='文件名')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '记录类文件',
            },
        ),
        migrations.AddField(
            model_name='technifilename',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='technifilename',
            name='result',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='文件全名'),
        ),
        migrations.AddField(
            model_name='technifilename',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name_generate.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name_generate.ProjectClass', verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name_generate.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Module', verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Scheme', verbose_name='方案'),
        ),
        migrations.AddField(
            model_name='recordfilename',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='planfilename',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.Project', verbose_name='项目'),
        ),
    ]
