# Generated by Django 2.0.1 on 2019-09-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0005_auto_20190930_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technifilename',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
    ]
