# Generated by Django 2.0.1 on 2019-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0007_planfilename_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technifilename',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文件全名'),
        ),
    ]
