# Generated by Django 2.0.1 on 2019-10-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0008_auto_20190930_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfilename',
            name='result',
            field=models.CharField(max_length=60, null=True, verbose_name='文件全名'),
        ),
        migrations.AlterField(
            model_name='planfilename',
            name='result',
            field=models.CharField(max_length=60, null=True, verbose_name='文件全名'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='result',
            field=models.CharField(max_length=50, null=True, verbose_name='文件全名'),
        ),
    ]
