# Generated by Django 2.0.1 on 2019-10-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0009_auto_20191008_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfilename',
            name='projectclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_generate.ProjectClass', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectclass',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='代号'),
        ),
        migrations.AlterField(
            model_name='technifilename',
            name='result',
            field=models.CharField(max_length=50, verbose_name='文件全名'),
        ),
    ]
