# Generated by Django 2.0.1 on 2019-10-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_generate', '0010_auto_20191008_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfilename',
            name='projectclass',
        ),
        migrations.AddField(
            model_name='planfilename',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='recordfilename',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
    ]
